In [1]:
import numpy as np
from scipy.io import loadmat


data = loadmat('C:\\Users\\Galal\\Downloads\\My-Github\\CV_learning\\Sprint 3\\Sprint 3\\Andrew\\w3\\ex3data1.mat')

print(data) 
print(data['X']) 
print(data['y'])
print('X Shape = ' ,  data['X'].shape) 
print('Y Shape = ', data['y'].shape)

print(data['X'][0]) 
print(data['X'][0][155]) 
print('===================================================')





def sigmoid(z):
    return 1 / (1 + np.exp(-z))

def cost(theta, X, y, learningRate):
    theta = np.matrix(theta)
    X = np.matrix(X)
    y = np.matrix(y)
    first = np.multiply(-y, np.log(sigmoid(X * theta.T)))
    second = np.multiply((1 - y), np.log(1 - sigmoid(X * theta.T)))
    reg = (learningRate / 2 * len(X)) * np.sum(np.power(theta[:,1:theta.shape[1]], 2))
    return np.sum(first - second) / (len(X)) + reg


def gradient_with_loop(theta, X, y, learningRate):
    theta = np.matrix(theta)
    X = np.matrix(X)
    y = np.matrix(y)
    
    parameters = int(theta.ravel().shape[1])
    grad = np.zeros(parameters)
    
    error = sigmoid(X * theta.T) - y
    
    for i in range(parameters):
        term = np.multiply(error, X[:,i])
        
        if (i == 0):
            grad[i] = np.sum(term) / len(X)
        else:
            grad[i] = (np.sum(term) / len(X)) + ((learningRate / len(X)) * theta[:,i])
    
    return grad

def gradient(theta, X, y, learningRate):
    theta = np.matrix(theta)
    X = np.matrix(X)
    y = np.matrix(y)
    
    parameters = int(theta.ravel().shape[1])
    error = sigmoid(X * theta.T) - y
    
    grad = ((X.T * error) / len(X)).T + ((learningRate / len(X)) * theta)
    
    # intercept gradient is not regularized
    grad[0, 0] = np.sum(np.multiply(error, X[:,0])) / len(X)
    
    return np.array(grad).ravel()

from scipy.optimize import minimize

def one_vs_all(X, y, num_labels, learning_rate):
    rows = X.shape[0] #5000
    params = X.shape[1] #400
    
    # k X (n + 1) array for the parameters of each of the k classifiers
    all_theta = np.zeros((num_labels, params + 1))
    
    print('all_theta shape ' , all_theta.shape)
    # insert a column of ones at the beginning for the intercept term
    X = np.insert(X, 0, values=np.ones(rows), axis=1)
    print('X shape ' , X.shape)
    
    # labels are 1-indexed instead of 0-indexed
    for i in range(1, num_labels + 1):
        theta = np.zeros(params + 1)
        y_i = np.array([1 if label == i else 0 for label in y])
        y_i = np.reshape(y_i, (rows, 1))
        
        # minimize the objective function
        fmin = minimize(fun=cost, x0=theta, args=(X, y_i, learning_rate), method='TNC', jac=gradient)
        all_theta[i-1,:] = fmin.x
    
    return all_theta



rows = data['X'].shape[0]
params = data['X'].shape[1]

print('rows = ' ,rows)
print('params = ' , params)

print('===================================================')


all_theta = np.zeros((10, params + 1))

print('all_theta \n' , all_theta)
print('all_theta shape \n' , all_theta.shape)

print('===================================================')


X = np.insert(data['X'], 0, values=np.ones(rows), axis=1)


print(X) 
print('X Shape = ' ,  X.shape) 

print('===================================================')

theta = np.zeros(params + 1)

print('theta \n' , theta ) 

print('===================================================')


y_0 = np.array([1 if label == 0 else 0 for label in data['y']])

print('y_0')
print(y_0.shape)
print(y_0)

print('===================================================')

y_0 = np.reshape(y_0, (rows, 1))


print('y_0')
print(y_0.shape)
print(y_0)

print('===================================================')

print()
print('X.shape = ',X.shape)
print()
print('y.shape = ',y_0.shape)
print()
print('theta.shape = ',theta.shape)
print()
print('all_theta.shape = ',all_theta.shape)

print()
print('data array = ' , np.unique(data['y']))

print()




all_theta = one_vs_all(data['X'], data['y'], 1, 1)

print('Theta shape =   ' , all_theta.shape)
print('Theta = ')
print(all_theta)



def predict_all(X, all_theta):
    rows = X.shape[0]
    params = X.shape[1]
    num_labels = all_theta.shape[0]
    
    # same as before, insert ones to match the shape
    X = np.insert(X, 0, values=np.ones(rows), axis=1)
    
    # convert to matrices
    X = np.matrix(X)
    all_theta = np.matrix(all_theta)
    
    # compute the class probability for each class on each training instance
    h = sigmoid(X * all_theta.T)
    
    # create array of the index with the maximum probability
    h_argmax = np.argmax(h, axis=1)
    
    # because our array was zero-indexed we need to add one for the true label prediction
    h_argmax = h_argmax + 1
    
    return h_argmax

y_pred = predict_all(data['X'], all_theta)
correct = [1 if a == b else 0 for (a, b) in zip(y_pred, data['y'])]
accuracy = (sum(map(int, correct)) / float(len(correct)))
print ('accuracy = {0}%'.format(accuracy * 100))


{'__header__': b'MATLAB 5.0 MAT-file, Platform: GLNXA64, Created on: Sun Oct 16 13:09:09 2011', '__version__': '1.0', '__globals__': [], 'X': array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]]), 'y': array([[10],
       [10],
       [10],
       ...,
       [ 9],
       [ 9],
       [ 9]], dtype=uint8)}
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[10]
 [10]
 [10]
 ...
 [ 9]
 [ 9]
 [ 9]]
X Shape =  (5000, 400)
Y Shape =  (5000, 1)
[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
  0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
  0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
  0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
  0.

Theta shape =    (1, 401)
Theta = 
[[-3.70247923e-05  0.00000000e+00  0.00000000e+00  1.45740963e-10
  -1.26000455e-09 -1.07067746e-09 -2.29267679e-08 -2.08810311e-08
  -2.32624764e-11 -1.77197015e-08 -1.42717377e-08 -3.33472960e-09
   2.45288438e-09  4.29598330e-09  6.83398835e-09  9.29088003e-09
   5.08966538e-09  1.40383168e-09  4.28809850e-11 -1.79446415e-11
   0.00000000e+00 -1.99645435e-12  2.16948406e-11 -1.85206024e-09
   1.74264647e-08  2.23711412e-08 -5.02669587e-08 -1.41936274e-07
  -2.11236035e-07 -2.07880622e-07 -1.09764267e-07 -8.71206125e-09
   1.24087897e-08 -3.78652355e-09 -1.69655029e-08 -4.16799836e-08
  -1.74641866e-08  1.74915742e-09  6.56556687e-09  1.60534534e-09
   5.57721662e-10  1.48933210e-11 -3.36720618e-10  6.07719496e-10
   2.75179871e-08 -4.77049279e-08 -5.16705735e-07 -9.73763767e-07
  -1.19167524e-06 -9.55309663e-07 -5.09174929e-07 -3.56951563e-07
  -2.88959039e-07 -3.74443672e-07 -7.49724874e-07 -8.72934914e-07
  -4.58384936e-07 -2.05373487e-07 -7.7579

In [2]:
import numpy as np
neuron = 4

def sigmoid(x):
    return 1.0/(1+ np.exp(-x))

def sigmoid_derivative(x):
    return x * (1.0 - x)

class NeuralNetwork:
    def __init__(self, x, y):
        self.input      = x
        print('inputs \n' , self.input)
        print()
        self.weights1   = np.random.rand(self.input.shape[1],neuron) 
        print('weights1 \n',self.weights1)
        print()
        self.weights2   = np.random.rand(neuron,1)                 
        print('weights2 \n',self.weights2)
        print()
        self.y          = y
        print('y \n',self.y)
        print()
        self.output     = np.zeros(self.y.shape) # y hat
        print('output \n',self.output)
        print()
        
    def feedforward(self):
        self.layer1 = sigmoid(np.dot(self.input, self.weights1))
#        print('layer 1 \n',self.layer1)
#        print()        
        self.output = sigmoid(np.dot(self.layer1, self.weights2))
#        print('output \n',self.output)
#        print()
        
    def backprop(self):
        # application of the chain rule to find derivative of the loss function with respect to weights2 and weights1
        d_weights2 = np.dot(self.layer1.T, (2*(self.y - self.output) * sigmoid_derivative(self.output)))
#        print('d_weights2  \n',d_weights2  )
#        print()        
        d_weights1 = np.dot(self.input.T,
                            (np.dot(2*(self.y - self.output) * sigmoid_derivative(self.output),
                                    self.weights2.T) * sigmoid_derivative(self.layer1)))
#        print('d_weights1 \n',d_weights1)
#        print()        

        # update the weights with the derivative (slope) of the loss function
        self.weights1 += d_weights1
        self.weights2 += d_weights2


X = np.array([[0,0,1],
              [0,1,1],
              [1,0,1],
              [1,1,1]])

    
    
y = np.array([[0],
              [1],
              [1],
              [0]])

    
nn = NeuralNetwork(X,y)

for i in range(20000):
    nn.feedforward()
    nn.backprop()
#    print('--------------------------------')
#
print(nn.output)

inputs 
 [[0 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 1]]

weights1 
 [[0.47685081 0.20090804 0.19660352 0.47639515]
 [0.180767   0.77120165 0.12233924 0.98497443]
 [0.37113746 0.68731415 0.17412281 0.20701128]]

weights2 
 [[0.04139025]
 [0.2880263 ]
 [0.46987642]
 [0.78113601]]

y 
 [[0]
 [1]
 [1]
 [0]]

output 
 [[0.]
 [0.]
 [0.]
 [0.]]

[[0.0021908 ]
 [0.99475804]
 [0.99497068]
 [0.0056713 ]]
